create home-page
Igor-Klein-1988/allcom pull request #19
Opened 2023-11-12 20:17 UTC by DariaLavrushko

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on package.json
> +		"react-inlinesvg": "^4.1.0",
Why? Do you use it?

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on package.json
> +		"react-svg": "^16.1.29",
same

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on public/locales/en.json
> +		"main_text_part2": "for yourself!!",
it isn't "Auktionsgegenstände!!" or "аукционные лоты!!"

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/app/store.ts
>  // import counterReducer from '../features/counter/counterSlice';
delete it

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/features/products/Products.tsx
> +													<a className="product__items--link" href="product-details.html">
use NavLink

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/features/products/Products.tsx
> +															<a
use NavLink

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/features/products/Products.tsx
> +															<a className="product__items--action__btn" href="wishlist.html">
use NavLink

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/features/products/Products.tsx
> +															<a
use NavLink

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/features/products/productsSlice.ts
> +import ProductsState from './types/ProductsState';
add empty line

2023-11-12 20:38 UTC, Igor-Klein-1988 commented on src/index.scss
> +@import "./assets/scss/elements/_baner";
@import "./assets/scss/elements/_baner`.scss`

2023-11-12 20:41 UTC, DenysBabenko29 requested changes

2023-11-12 20:41 UTC, DenysBabenko29 commented on public/locales/de.json
> +		"wishlist": "Wunschliste"
"wishlist": "Merkzettel",

2023-11-12 20:41 UTC, DenysBabenko29 commented on src/features/products/baner/Baner.tsx
> +									{' '}
need to?

2023-11-12 20:44 UTC, DariaLavrushko commented on public/locales/en.json
> +		"main_text_part2": "for yourself!!",
What is it?

2023-11-12 20:46 UTC, DariaLavrushko commented on src/features/products/baner/Baner.tsx
> +									{' '}
Need empty line hire

2023-11-13 16:26 UTC, Igor-Klein-1988 approved these changes

2023-11-13 16:27 UTC, merged